// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using employeeMan.Models;

namespace employeeMan.Migrations
{
    [DbContext(typeof(employeeContext))]
    partial class employeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("employeeMan.Models.employee", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("empl_adr")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("empl_dep")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("empl_id")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("empl_nm")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("id");

                    b.ToTable("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
